### ISSUE TITLE
Set up TravisCI to check for Signed Off By

### ISSUE THREAD

**Issue by missaugustina** [BonnyCI/mateys-ahoy#11]

**Comment by SarahZuk** [comment]
Should we schedule a time to do this together?

**Comment by missaugustina** [comment]
hey @SarahZuk sorry I didn't get back to you sooner! Let's go ahead and focus on the other things, I think this might just end up being a bit distracting and confusing. I just did this for the meatmap project and I'm working on it for this project now.

**Comment by missaugustina** [comment]
Needs to be done for R language, currently just used Python because R was failing
